application: bma-trails
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /v1/.*
  script: mockapi.app

- url: /
  script: mappage.app

builtins:
- datastore_admin: on
- appstats: on

libraries:
- name: django
  version: "1.2"